name: Main Branch CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

env:
  REGISTRY: ghcr.io
  CLINICBOOKING_IMAGE_NAME: ${{ format('{0}/{1}/clinicbooking-api', 'ghcr.io', github.repository_owner) }}

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Set up Docker image names
        run: |
          echo "CLINICBOOKING_IMAGE_NAME_LOWER=$(echo ${{ env.REGISTRY }}/${{ github.repository }}/clinicbooking-api | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and test Clinic Booking API
        run: |
          dotnet restore BE/ClinicBooking/ClinicBooking.csproj
          dotnet build BE/ClinicBooking/ClinicBooking.csproj --configuration Release
          # Add tests if you have them
          # dotnet test ClinicBooking.Tests/ClinicBooking.Tests.csproj

      - name: Build and push Docker images
        run: |
          # Build and push CLINICBOOKING
          docker build -t ${{ env.CLINICBOOKING_IMAGE_NAME_LOWER }}:${{ github.sha }} -t ${{ env.CLINICBOOKING_IMAGE_NAME_LOWER }}:latest ./BE/ClinicBooking
          docker push ${{ env.CLINICBOOKING_IMAGE_NAME_LOWER }}:${{ github.sha }}
          docker push ${{ env.CLINICBOOKING_IMAGE_NAME_LOWER }}:latest

      